spring:
  cloud:
    config:
      uri: ${CONFIG_SERVER_URI:http://localhost:8888}
  config:
    import: "configserver:"
  application:
    name: auth-service
  profiles:
    active: ${ACTIVE_PROFILE:dev}

