# config-server/src/main/resources/config/mail-service-prod.yml

server:
  port: ${SERVER_PORT:9020}

spring:
  cloud:
    openfeign:
      clients:
        auth-service:
          url: ${AUTH_SERVICE_URL:http://localhost:9000}

  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres-service}:${DB_PORT:5432}/${DB_NAME:chat_app_prod}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  data:
    redis:
      host: ${REDIS_HOST:redis-service}
      port: ${REDIS_PORT:6379}
#      password: ${REDIS_PASSWORD}

  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false

  mail:
    host: ${EMAIL_HOST:smtp.gmail.com}
    port: ${EMAIL_PORT:587}
    username: ${EMAIL_ID}
    password: ${EMAIL_PASSWORD}
    verify:
      host: ${MAIL_VERIFY_HOST}
    default-encoding: UTF-8
    properties:
      mail:
        mime:
          charset: UTF-8
        smtp:
          writetimeout: 10000
          connectiontimeout: 10000
          timeout: 10000
          auth: true
          starttls:
            enable: true
            required: true

raceapplication:
  security:
    jwt:
      secret-key: ${JWT_SECRET} # Mutlaka environment'tan al
      expiration: ${JWT_EXPIRATION:900000} # 15 dakika production'da
      refresh-token:
        expiration: ${JWT_REFRESH_EXPIRATION:604800000}

# Production logging
#logging:
#  level:
#    com.vky: INFO
#    org.springframework.security: WARN
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#  endpoint:
#    health:
#      show-details: always
