# config-server/src/main/resources/config/auth-service-dev.yml
server:
  port: ${SERVER_PORT:9020}

spring:
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:veysel}
    password: ${RABBITMQ_PASSWORD:123}

  cloud:
    openfeign:
      clients:
        auth-service:
          url: ${AUTH_SERVICE_URL:http://localhost:9000}

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:chat_app_dev}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:12345}

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}


  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mail:
    host: ${EMAIL_HOST:smtp.gmail.com}
    port: ${EMAIL_PORT:587}
    username: ${EMAIL_ID}
    password: ${EMAIL_PASSWORD}
    verify:
      host: ${MAIL_VERIFY_HOST:http://localhost:3000}
    default-encoding: UTF-8
    properties:
      mail:
        mime:
          charset: UTF
        smtp:
          writetimeout: 10000
          connectiontimeout: 10000
          timeout: 10000
          auth: true
          starttls:
            enable: true
            required: true

# Development logging
logging:
  level:
    com.vky: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always