# config-server/src/main/resources/config/contacts-service.yml
spring:
  application:
    name: contacts-service

  jpa:
    generate-ddl: true
    show-sql: ${SHOW_SQL:false}
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: ${FORMAT_SQL:false}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
  instance:
    instance-id: ${spring.application.name}:${server.port}

# Base logging configuration
logging:
  level:
    com.vky: ${LOG_LEVEL:INFO}
    org.springframework.web: ${WEB_LOG_LEVEL:INFO}
    org.springframework.cloud: ${CLOUD_LOG_LEVEL:INFO}

# Management endpoints (eğer actuator kullanıyorsanız)
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized