spring:
  cloud:
    config:
      uri: ${CONFIG_SERVER_URI:http://localhost:8888}
  config:
    import: "configserver:"
  application:
    name: contacts-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
