server:
  port: ${SERVER_PORT}
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    listener:
      simple:
        concurrency: 5
        max-concurrency: 20
        prefetch: 50

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

  websocket:
    max-text-message-size: 512KB
    max-binary-message-size: 512KB

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER}
    registryFetchIntervalSeconds: 30
  instance:
    instance-id: ${spring.application.name}:${server.port}
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration: ${JWT_EXPIRATION}
      refresh-token:
        expiration: ${JWT_REFRESH_EXPIRATION}
      issuer: ${JWT_ISSUER}

logging:
  level:
    root: INFO
    com.vky: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: WARN
    org.springframework.data.redis: WARN
    org.springframework.data.mongodb: WARN

    org.springframework.web.socket: DEBUG
    org.springframework.messaging: DEBUG
    org.springframework.messaging.simp: DEBUG
    org.springframework.web.socket.messaging: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
