#Database
MONGODB_USERNAME: veysel
MONGODB_PASSWORD: veysel
MONGODB_HOST: localhost
MONGODB_PORT: 27017
MONGODB_DB: chat_app_dev
RABBITMQ_HOST: localhost
RABBITMQ_PORT: 5672
RABBITMQ_USERNAME: veysel
RABBITMQ_PASSWORD: 123
#Server
SERVER_PORT: 9040
ACTIVE_PROFILE: dev

REDIS_HOST: 127.0.0.1
REDIS_PORT: 6379


AUTH_PORT: 9000
MAIL_PORT: 9020
USER_PORT: 9010
CONTACTS_PORT: 9030
CHAT_PORT: 9040



