#Database
MONGODB_USERNAME: veysel
MONGODB_PASSWORD: veysel
MONGODB_HOST: localhost
MONGODB_PORT: 27017
MONGODB_DB: chat_app_prod

#Server
SERVER_PORT: 9041
ACTIVE_PROFILE: prod


AUTH_PORT: 9001
MAIL_PORT: 9021
USER_PORT: 9011
CONTACTS_PORT: 9031
CHAT_PORT: 9041



