#Database
MONGODB_USERNAME: veysel
MONGODB_PASSWORD: veysel
MONGODB_HOST: localhost
MONGODB_PORT: 27017
MONGODB_DB: chat_app_dev

#Server
SERVER_PORT: 9040
ACTIVE_PROFILE: dev


AUTH_PORT: 9000
MAIL_PORT: 9020
USER_PORT: 9010
CONTACTS_PORT: 9030
CHAT_PORT: 9040



