server:
  port: ${SERVER_PORT:9040}

spring:
  application:
    name: chat-service
  profiles:
    active: ${ACTIVE_PROFILE:dev}
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
  eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
    instance:
      instance-id: ${spring.application.name}:${server.port}
  data:
    mongodb:
      username: ${MONGODB_USERNAME}
      password: ${MONGODB_PASSWORD}
      host: ${MONGODB_HOST}
      port: ${MONGODB_PORT}
      database: ${MONGODB_DB}
      authentication-database: admin
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  redis:
    host: localhost
    port: 6379
management:
  endpoints:
    web:
      exposure:
        include: "*"


raceapplication:
  url:
    auth: http://localhost:${AUTH_PORT}/
    mail: http://localhost:${MAIL_PORT}/
    user: http://localhost:${USER_PORT}/
    contacts: http://localhost:${CONTACTS_PORT}/
    chat: http://localhost:${CHAT_PORT}/

