server:
  port: ${SERVER_PORT:9010}

spring:
  application:
    name: user-service
  profiles:
    active: ${ACTIVE_PROFILE:dev}
  eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
    instance:
      instance-id: ${spring.application.name}:${server.port}
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
  datasource:
    url: jdbc:postgresql://${POSTGRES_SQL_HOST}:${POSTGRES_SQL_PORT}/${POSTGRES_SQL_DB}
    username: ${POSTGRES_SQL_USERNAME}
    password: ${POSTGRES_SQL_PASSWORD}
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  web:
    cors:
      allowed-origins: "*"
      allowed-methods: "*"
      allowed-headers: "*"

raceapplication:
  url:
    auth: http://localhost:${AUTH_PORT}/
    mail: http://localhost:${MAIL_PORT}/
    user: http://localhost:${USER_PORT}/
    friendships: http://localhost:${FRIENDSHIPS_PORT}/

application:
  security:
    jwt:
      secret-key: ${SECRET_KEY}
