# config-server/src/main/resources/config/auth-service-prod.yml
server:
  port: ${SERVER_PORT:9000}

spring:
  rabbitmq:
    host: ${RABBITMQ_HOST:rabbitmq-service}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

  cloud:
    openfeign:
      clients:
        mail-service:
          url: ${MAIL_SERVICE_URL:http://mail-service:9020}
        user-service:
          url: ${USER_SERVICE_URL:http://user-service:9010}

  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres-service}:${DB_PORT:5432}/${DB_NAME:chat_app_prod}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
#    hikari:
#      maximum-pool-size: ${DB_POOL_SIZE:20}
#      connection-timeout: ${DB_CONNECTION_TIMEOUT:30000}
#      idle-timeout: ${DB_IDLE_TIMEOUT:600000}
#      max-lifetime: ${DB_MAX_LIFETIME:1800000}

  data:
    redis:
      host: ${REDIS_HOST:redis-service}
      port: ${REDIS_PORT:6379}
#      password: ${REDIS_PASSWORD}
#      timeout: ${REDIS_TIMEOUT:2000ms}

  # Production specific settings
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate # Production'da validate kullan
    properties:
      hibernate:
        format_sql: false

raceapplication:
  security:
    jwt:
      secret-key: ${JWT_SECRET} # Mutlaka environment'tan al
      expiration: ${JWT_EXPIRATION:900000} # 15 dakika production'da
      refresh-token:
        expiration: ${JWT_REFRESH_EXPIRATION:604800000}

# Production logging
#logging:
#  level:
#    com.vky: INFO
#    org.springframework.web: WARN
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
#    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
#  file:
#    name: /var/log/auth-service.log
#
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: health,info,metrics,prometheus
#  endpoint:
#    health:
#      show-details: never
#  metrics:
#    export:
#      prometheus:
#        enabled: true