spring:
  application:
    name: api-gateway
  main:
    web-application-type: REACTIVE
  eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/

server:
  port: 8080

