spring:
  main:
    web-application-type: REACTIVE
    allow-bean-definition-overriding: true
  data:
    redis:
      host: localhost
      port: 6379
  cloud:
    gateway:
      server:
        webflux:
          httpclient:
            pool:
              max-connections: 100
              max-idle-time: 30s
            connect-timeout: 5000
            response-timeout: 30s
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka/}
  instance:
    instance-id: ${spring.application.name}:${server.port}

    #logging:
    #level:
    #reactor.netty: DEBUG
    #io.netty: DEBUG
    #org.springframework.web: DEBUG
    #org.springframework.web.reactive.socket: DEBUG
    #org.springframework.cloud.gateway: DEBUG

server:
  port: 8080


application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 60000
      refresh-token:
        expiration: 604800000